spring:
  application:
    name: ACCOUNT
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/account-service?ApplicationName=IDEA
    username: ${db_user}
    password: ${db_password}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      instance:
        preferIpAddress: true
feign:
  client:
    config:
      default:
        eurekaEnabled: true
server:
  port: 8082
