spring:
  application:
    name: CLASSIFIER
  data:
    mongodb:
      host: localhost
      port: 27017
      username: ${db_user}
      password: ${db_password}
      database: classifier
  kafka:
    bootstrap-servers:
      - localhost:9092
    producer:
      keySerializer: org.springframework.kafka.support.serializer.JsonSerializer
      valueSerializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: 8084


